CREATE DATABASE IF NOT EXISTS faq CHARACTER SET utf8 COLLATE utf8_general_ci; 

USE faq;

SET storage_engine = InnoDB;

CREATE TABLE faq.Problemas (
	IDProblema INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NomeProblema VARCHAR(150) NOT NULL,
	SolucaoProblema TEXT NOT NULL,
	created_at DATETIME,
	updated_at DATETIME
);

CREATE TABLE faq.Tags (
	IDTag INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NomeTag VARCHAR(50) NOT NULL
);

CREATE TABLE faq.TagMap (
	IDTagMap INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	IDProblema INT NOT NULL,
	IDTag INT NOT NULL,
	FOREIGN KEY (IDProblema) REFERENCES Problemas(IDProblema),
	FOREIGN KEY (IDTag) REFERENCES Tags(IDTag)
);